title: Tony's Blog
author: Tony
email: stnet253@gmail.com
description: Welcome to tony's blog 自由軟體愛好者~喜歡不斷的思考各種問題，有新的事物都會想去學習嘗試 做實驗並熱衷研究 沒有所謂頂天的技術 只有謙虛及不斷的學習 精進專業，本站主要以分享系統及網路相關知識、資源而建立。
twitter_username: jekyllrb
github_username:  jekyll
lang: en-US
url: "https://github.manpc.tk"


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
date_format: "%a, %b %d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown

remote_theme: llorephie/jekyll-bootstrap

exclude:
  - Gemfile
  - Gemfile.lock

theme: jekyll-theme-hacker
